### ISSUE TITLE
Add option to send Keystrokes for "Click on empty taskbar space" Mod

### ISSUE THREAD

**Issue by jvaldiviezo9** [m1lhaus/windhawk-mods#8]
Hi @m1lhaus 

While using this mod, I realized that it could be very handy to have the ability to configure keystrokes. For example, I found it convenient to use the middle click on empty space to open a new File Explorer window (Win + E). I also realized that there might be cases where users would like to execute a specific command, so having this functionality as a user-configurable variable would be nice.

Thanks in advance!

**Comment by m1lhaus** [comment]
Sending keypress to the system should be fairly simple since it is already used to open Start menu, send Win+Tab etc. The question is how to implement this in Settings tab with respect to Windhawk API 🤔

Regrading arbitrary command, it is already planned, see https://github.com/m1lhaus/windhawk-mods/issues/2.

**Comment by jvaldiviezo9** [comment]
@m1lhaus Excellent and thanks for the quick reply!
